=== DucHuyFDev/THHTPM_HaUI/KTTX1_24_7/src/kttx1_24_7/BenhNhan.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

	<xs:simpleType name="songaynvType">
		<xs:restriction base="xs:int">
			<xs:maxExclusive value="40"></xs:maxExclusive>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tenkhoaType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Khoa thần kinh"></xs:enumeration>
			<xs:enumeration value="Khoa nội"></xs:enumeration>
			<xs:enumeration value="Khoa ngoại"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="benhNhanType">
		<xs:sequence>
			<xs:element name="hoten" type="xs:string"></xs:element>
			<xs:element name="ngaysinh" type="xs:date"></xs:element>
		</xs:sequence>
		<xs:attribute name="maso" type="xs:string"></xs:attribute>
		<xs:attribute name="songay" type="songaynvType"></xs:attribute>
	</xs:complexType>

	<xs:element name="khoa">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tenkhoa" type="tenkhoaType"></xs:element>
				<xs:element name="benhnhan" type="benhNhanType" minOccurs="0" maxOccurs="unbounded"></xs:element>
			</xs:sequence>
			<xs:attribute name="makhoa" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DS">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="khoa" minOccurs="0" maxOccurs="10"></xs:element>
			</xs:sequence>
			<xs:attribute name="tenbv" type="xs:string"></xs:attribute>
		</xs:complexType>
		<xs:unique name="uniqueMaKhoa">
			<xs:selector xpath="DS/khoa"></xs:selector>
			<xs:field xpath ="@makhoa"></xs:field>
		</xs:unique>
	</xs:element>
	
</xs:schema>

=== DucHuyFDev/THHTPM_HaUI/KTTX1_24_7/src/kttx1_24_7/BenhNhan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<DS tenbv="Bệnh viện Bạch Mai"
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='BenhNhan.xsd'>
    <khoa makhoa="A01">
        <tenkhoa>Khoa thần kinh</tenkhoa>
		<benhnhan maso="bn001" songay="20">
			<hoten>Lê Thị Lan</hoten>
			<ngaysinh>1988-12-21</ngaysinh>
		</benhnhan>
		<benhnhan maso="bn002" songay="25">
			<hoten>Lê Thị Huyền</hoten>
			<ngaysinh>1990-11-01</ngaysinh>
		</benhnhan>
		<benhnhan maso="bn003" songay="7">
			<hoten>Ngô Anh Vũ</hoten>
			<ngaysinh>2004-10-04</ngaysinh>
		</benhnhan>
    </khoa>
    <khoa makhoa="A02">
        <tenkhoa>Khoa ngoại</tenkhoa>
		<benhnhan maso="bn004" songay="10">
			<hoten>Lê Thị Luyến</hoten>
			<ngaysinh>1991-11-21</ngaysinh>
		</benhnhan>
		<benhnhan maso="bn005" songay="2">
			<hoten>Ngô Anh Thắng</hoten>
			<ngaysinh>1995-01-14</ngaysinh>
		</benhnhan>
		<benhnhan maso="bn006" songay="17">
			<hoten>Bùi Xuân Huấn</hoten>
			<ngaysinh>1985-11-15</ngaysinh>
		</benhnhan>
    </khoa>
    

</DS>
