=== DucHuyFDev/THHTPM_HaUI/De3_LeDucHuy_2022600377/src/de3_leduchuy_2022600377/congty.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

	<!--Kiểu dữ liệu số điện thoại-->
	<xs:simpleType name="sdtType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{4}-\d{3}-\d{3}"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>

	<!--Kiểu dữ liệu tên sản phẩm-->
	<xs:simpleType name="tenspType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"></xs:minLength>
		</xs:restriction>
	</xs:simpleType>

	<!--Kiểu dữ liệu giá-->
	<xs:simpleType name="giaType">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="100"></xs:minInclusive>
			<xs:maxInclusive value="900"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>

	<!--Kiểu phức hợp sản phẩm-->
	<xs:complexType name="sanPhamType">
		<xs:sequence>
			<xs:element name="MaSP" type="xs:string"></xs:element>
			<xs:element name="TenSP" type="tenspType"></xs:element>
			<xs:element name="GiaTien" type="giaType"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<!--Kiểu phức hợp phòng-->
	<xs:complexType name="phongType">
		<xs:sequence>
			<xs:element name="DienThoai" type="sdtType"></xs:element>
			<xs:element name="SanPham" type="sanPhamType" minOccurs="3" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		<xs:attribute name="MaPhong" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>
	
	<!--Tạo element root công ty-->
	<xs:element name="CongTy">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Phong" type="phongType" minOccurs="2" maxOccurs="unbounded"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DucHuyFDev/THHTPM_HaUI/De3_LeDucHuy_2022600377/src/de3_leduchuy_2022600377/congty.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xsl-stylesheet type="text/xsl" href="congty.xsl"?>


<CongTy
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='congty.xsd'>
    <Phong MaPhong="m01">
        <DienThoai>0234-232-423</DienThoai>
        <SanPham>
            <MaSP>sp01</MaSP>
            <TenSP>Điện thoại 1</TenSP>
            <GiaTien>200</GiaTien>
        </SanPham>
        <SanPham>
            <MaSP>sp02</MaSP>
            <TenSP>Điện thoại 2</TenSP>
            <GiaTien>650</GiaTien>
        </SanPham>
        <SanPham>
            <MaSP>sp03</MaSP>
            <TenSP>Ipad 01</TenSP>
            <GiaTien>150</GiaTien>
        </SanPham>
    </Phong>
    <Phong MaPhong="m02">
        <DienThoai>0985-650-918</DienThoai>
        <SanPham>
            <MaSP>sp04</MaSP>
            <TenSP>Tủ lạnh</TenSP>
            <GiaTien>845</GiaTien>
        </SanPham>
        <SanPham>
            <MaSP>sp05</MaSP>
            <TenSP>Lò vi sóng</TenSP>
            <GiaTien>825</GiaTien>
        </SanPham>
        <SanPham>
            <MaSP>sp06</MaSP>
            <TenSP>Bàn là</TenSP>
            <GiaTien>625</GiaTien>
        </SanPham>
    </Phong>

</CongTy>
